tap "homebrew/cask" if OS.mac?
tap "buo/cask-upgrade" if OS.mac?
tap "pulumi/tap"
brew "mas" if OS.mac?
brew "aircrack-ng"
brew "difftastic"
brew "direnv"
brew "emacs"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "git-spice"
brew "jj"
brew "node"
brew "jupyterlab"
brew "lazygit"
brew "libmagic"
brew "libpq"
brew "luajit"
brew "luarocks"
brew "navi"
brew "neovim"
brew "nginx"
brew "pipx"
brew "pkgconf"
brew "pnpm"
brew "poppler"
brew "pyenv"
brew "ripgrep"
brew "starship"
brew "tesseract"
brew "tmux"
brew "tree-sitter-cli"
brew "typescript"
brew "valkey"
brew "xan"
brew "yadm"
brew "yarn"
brew "pulumi/tap/pulumi"
cask "1password-cli" if OS.mac?
cask "caffeine" if OS.mac?
cask "claude-code" if OS.mac?
cask "fx-cast-bridge" if OS.mac?
cask "ghostty" if OS.mac?
cask "libreoffice" if OS.mac?
cask "librewolf" if OS.mac?
cask "neovide-app" if OS.mac?
cargo "cargo-pgrx"
